### ISSUE TITLE
I need help with a bundling problem in Lit 2.0/TypeScript monorepo

### ISSUE THREAD

**Issue by kaityama** [AlaskaAirlines/auro-icon#43]
# General Support Request

## Support request
Hey there! I'm a dev from Seats and we are kicking off our newest tech initiative in updating our frontend to a Lit 2.0 component monorepo. We've decided to use TypeScript.

It appears I'm having issues with my bundling because even after running `npm i @alaskaairux/auro-icon` and it appearing in my package.json, with the following code, `auro-icon` is appearing as undefined in the browser console when running `customElements.get('auro-icon')`.

### Code:

```import { html, LitElement } from 'lit';
import { ClassInfo, classMap } from 'lit/directives/class-map.js';
import { property, customElement } from 'lit/decorators.js';
import '@alaskaairux/auro-icon';

import { styles } from './seat.styles.js';

export enum SeatProduct {
  First = 'first',
  Premium = 'premium',
  Refundable = 'refundable',
  Main = 'main',
  Saver = 'saver',
  UMNR = 'umnr',
  Unavailable = 'unavailable',
  Occupied = 'occupied',
  None = 'none',
}

@customElement('seats-seat')
export class Seat extends LitElement {
  static styles = styles;

  @property({ type: String }) product = SeatProduct.None;

  @property({ type: Boolean }) unavailable = false;

  @property({ type: Boolean }) active = false;

  @property({ type: Boolean }) selected = false;

  @property({ type: Boolean }) occupied = false;

  onClick() {
    this.dispatchEvent(
      new CustomEvent('seatClicked', {
        bubbles: true,
        composed: true,
        detail: {},
      })
    );
  }

  getSeatClasses = (): ClassInfo => {
    const showProductClass = (product: SeatProduct): boolean =>
      !this.selected &&
      !this.unavailable &&
      this.product.toLowerCase() === product.toLowerCase();

    const classes = {
      active: this.active,
      selected: this.selected,
      unavailable: this.unavailable,
      occupied: this.occupied,
      first: showProductClass(SeatProduct.First),
      premium: showProductClass(SeatProduct.Premium),
      refundable: showProductClass(SeatProduct.Refundable),
      main: showProductClass(SeatProduct.Main),
      saver: showProductClass(SeatProduct.Saver),
      umnr: showProductClass(SeatProduct.UMNR),
    };

    return classes;
  };

  render() {
    const seatClasses = this.getSeatClasses();
    return html`<button class="${classMap(seatClasses)}" @click=${this.onClick}>
      <auro-icon category="interface" name="star-filled" customSize></auro-icon>
      <slot></slot>
    </button>`;
  }
}
```

## Context
In this example, I am just trying to get an `auro-icon` to work in a seat and have decided to use the Premium Class `star-filled` icon. In the future, this would need to be expanded to more icons and the seat icon will be programatically displayed.

I really just want to get `auro-icon` running in a good, non-hacky way so we can move forward with more Auro icons in this project. 

## Your Environment

* Version used: 3.2.0
* Browser Name and version: Chrome 100.0.4896.127
* Operating System and version (desktop or mobile): Desktop MacOS Monterey 12.1
* Link to your project: [seats-ui-components repo feature branch feature/icon](https://github.com/Alaska-ECommerce/seats-ui-components/tree/feature/icon)

**Comment by blackfalcon** [comment]
I think I know the issue. `auro-icon` is not a Lit2.0 element and you cannot create a nested dependency on a > Lit2.0 element inside a Lit2.0 element. 

For this, and other reasons, we have taken this position as a best practice.
https://auro.alaskaair.com/generator/best-practice#:~:text=Direct%20or%20peer%20dependency%20elements

If you made auro-icon a peer dependency versus a direct dependency, I am pretty sure that this will address your issue.

**Comment by geoffrich** [comment]
Another option is to import the `star-filled` icon directly and render it with [`unsafeSVG`](https://lit.dev/docs/templates/directives/#unsafesvg).

```js
import {html, css, LitElement} from 'lit';
import { unsafeSVG } from 'lit/directives/unsafe-svg.js';
import star from '@alaskaairux/icons/dist/icons/interface/star-filled_es6';

export class IconTest extends LitElement {
  static styles = css`
      .icon { 
        color: rebeccapurple; 
      }`
  render() {
    return html`<p>Hello! <span class="icon">${unsafeSVG(star.svg)}</span></p>`;
  }
}
customElements.define('icon-test', IconTest);
```

[Live demo](https://lit.dev/playground/#project=W3sibmFtZSI6InNpbXBsZS1ncmVldGluZy5qcyIsImNvbnRlbnQiOiJpbXBvcnQge2h0bWwsIGNzcywgTGl0RWxlbWVudH0gZnJvbSAnbGl0JztcbmltcG9ydCB7IHVuc2FmZVNWRyB9IGZyb20gJ2xpdC9kaXJlY3RpdmVzL3Vuc2FmZS1zdmcuanMnO1xuaW1wb3J0IHN0YXIgZnJvbSAnQGFsYXNrYWFpcnV4L2ljb25zL2Rpc3QvaWNvbnMvaW50ZXJmYWNlL3N0YXItZmlsbGVkX2VzNic7XG5cbmV4cG9ydCBjbGFzcyBJY29uVGVzdCBleHRlbmRzIExpdEVsZW1lbnQge1xuICBzdGF0aWMgc3R5bGVzID0gY3NzYFxuICAgICAgLmljb24geyBcbiAgICAgICAgY29sb3I6IHJlYmVjY2FwdXJwbGU7IFxuICAgICAgfWBcbiAgcmVuZGVyKCkge1xuICAgIHJldHVybiBodG1sYDxwPkhlbGxvISA8c3BhbiBjbGFzcz1cImljb25cIj4ke3Vuc2FmZVNWRyhzdGFyLnN2Zyl9PC9zcGFuPjwvcD5gO1xuICB9XG59XG5jdXN0b21FbGVtZW50cy5kZWZpbmUoJ2ljb24tdGVzdCcsIEljb25UZXN0KTtcbiJ9LHsibmFtZSI6ImluZGV4Lmh0bWwiLCJjb250ZW50IjoiPCFET0NUWVBFIGh0bWw-XG48aGVhZD5cbiAgPHNjcmlwdCB0eXBlPVwibW9kdWxlXCIgc3JjPVwiLi9zaW1wbGUtZ3JlZXRpbmcuanNcIj48L3NjcmlwdD5cbiAgPGxpbmsgcmVsPVwic3R5bGVzaGVldFwiIGhyZWY9XCJodHRwczovL3VucGtnLmNvbS9AYWxhc2thYWlydXgvZGVzaWduLXRva2Vuc0AzLjguMC9kaXN0L3Rva2Vucy9DU1NDdXN0b21Qcm9wZXJ0aWVzLmNzc1wiPlxuPC9oZWFkPlxuPGJvZHk-XG4gIDxpY29uLXRlc3Q-PC9pY29uLXRlc3Q-XG48L2JvZHk-XG4ifSx7Im5hbWUiOiJwYWNrYWdlLmpzb24iLCJjb250ZW50Ijoie1xuICBcImRlcGVuZGVuY2llc1wiOiB7XG4gICAgXCJsaXRcIjogXCJeMi4wLjBcIixcbiAgICBcIkBsaXQvcmVhY3RpdmUtZWxlbWVudFwiOiBcIl4xLjAuMFwiLFxuICAgIFwibGl0LWVsZW1lbnRcIjogXCJeMy4wLjBcIixcbiAgICBcImxpdC1odG1sXCI6IFwiXjIuMC4wXCJcbiAgfVxufSIsImhpZGRlbiI6dHJ1ZX1d)

I generally render icons this way in my projects instead of auro-icon, because then the icon SVG can be directly bundled into my component instead of needing to fetch from the network at runtime. But I'm not sure if that's a common practice or not.

**Comment by blackfalcon** [comment]
@geoffrich you are not wrong. This is similar to what we have in the docs https://github.com/AlaskaAirlines/icons#lit-element

Options... that's what we are all about.
