### ISSUE TITLE
auro-icon: index is pointed to `src` instead of `dist`

### ISSUE THREAD

**Issue by Izook** [AlaskaAirlines/auro-icon#73]
## Describe the bug

The delivered version of `index.js` has a dependency on `./src/auro-icon.js` which is not in the delivered package. We should be depending on `./dist/auro-icon.js`

## To Reproduce

1. Consume package from npm or unpkg or any other npm package CDN
1. Observe `Failed to resolve './src/auro-icon' from '...'` error. 

## Expected behavior

The delivered package uses the `./dist/auro-icon.js` that exists instead of `./src/auro-icon`. 

## Screenshots

![image](https://user-images.githubusercontent.com/23248722/232561435-c2c9e79c-e188-412b-951f-8e0bbecab46a.png)

## Desktop (please complete the following information):

- All Desktops

## Smartphone (please complete the following information):

- All Smartphones

**Comment by blackfalcon** [comment]
The issue is related to the fact that the src resources are not included with the npm package. See the following link to see what is included with the current npm package. 
https://www.runpkg.com/?@alaskaairux/auro-header@1.5.3/index.js

See this file as a reference to correct. 
https://github.com/AlaskaAirlines/auro-hyperlink/blob/main/.npmignore

## Exit criteria 

This issue can be closed once the update includes the necessary components of the source files.
