### ISSUE TITLE
Release is missing required assets 

### ISSUE THREAD

**Issue by AuroDesignSystem** [AlaskaAirlines/auro-icon#74]
### Please verify the version of auro-badge you have installed

3.4.1

### Please describe the bug

The delivered version of `index.js` has a dependency on `./src/auro-icon.js` which is not in the delivered package. We need to update the package and include `./src/auro-icon.js`

### Expected behavior

The installed element should operate as expected. 

> This issue was copied from [#86](https:&#x2F;&#x2F;github.com&#x2F;AlaskaAirlines&#x2F;auro-header&#x2F;issues&#x2F;86) by @blackfalcon.

**Comment by blackfalcon** [comment]
The issue is related to the fact that the src resources are not included with the npm package. 

See this file as a reference to correct. 
https://github.com/AlaskaAirlines/auro-hyperlink/blob/main/.npmignore

## Exit criteria 

This issue can be closed once the update includes the necessary components of the source files.
